### ISSUE TITLE
Image files not opening

### ISSUE THREAD

**Issue by lmontel** [FastTrackOrg/FastTrack#17]
Hi Benjamin, 

System : Windows 
Distribution : Win10
FastTrack version : 5.3.2

I can't open any of my image files, I get "Error no image found" or "Error no file found". I downloaded and opened the demonstration zebrafish movie with no problem, but none of my images can be opened. I attached an example of image that generates the error.

![mdck-290321-HOESCHT10012](https://user-images.githubusercontent.com/10143097/120611912-eef0fd80-c454-11eb-9f87-e331107a1dc9.png)
 

See you, 

-- 
Lorraine

**Comment by bgallois** [comment]
Hi.
Can you provide a small image sequence/video sample (10-20 images is sufficient) that can reproduce the error?

**Comment by bgallois** [comment]
Should be fixed with 62225c8636cb8fadc83478d9a27e139bf4dbed25 and 477e51c06ea3910480b5d859fd7daa82a87a0b05 and available in the latest nightly build https://github.com/FastTrackOrg/FastTrack/tree/continuous and in the upcoming v5.3.3.
