### ISSUE TITLE
Add AppStream metadata?

### ISSUE THREAD

**Issue by musicinmybrain** [FastTrackOrg/FastTrack#20]
Would you consider adding AppStream metadata to the repository? See https://www.freedesktop.org/software/appstream/metainfocreator/#/guiapp. There is also some useful information at https://docs.fedoraproject.org/en-US/packaging-guidelines/AppData/.

This would be very beneficial for packaging in Linux distributions. It’s possible to package FastTrack without it, but the metadata means FastTrack can be discovered and managed in tools like GNOME Software Center.

It is awkward to add this metadata downstream because any metadata contents, including linked screenshots, must be available under one of a handful of extremely permissive licenses, so descriptions and screenshots from the upstream repository can’t be used without upstream making them available under an alternative license.

**Comment by bgallois** [comment]
Added with commit ff3816295f0d223d2c47a8be4ca9c523f88639a9

**Comment by musicinmybrain** [comment]
Thanks! I’ll be using this right away, packaging FastTrack as `fasttrack` for Fedora Linux.
